# Generated by Django 5.1.6 on 2025-02-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juez', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problema',
            name='archivo_pruebas',
        ),
        migrations.AddField(
            model_name='problema',
            name='enunciado',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problema',
            name='entrada_ejemplo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problema',
            name='salida_ejemplo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
