# Generated by Django 5.1.6 on 2025-02-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juez', '0002_remove_problema_archivo_pruebas_problema_enunciado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='enunciado',
            field=models.TextField(default='Enunciado no disponible'),
        ),
    ]
