# Generated by Django 5.1.6 on 2025-02-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juez', '0003_alter_problema_enunciado'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='entradas_prueba',
            field=models.TextField(default=0, help_text='Entradas de prueba separadas por líneas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problema',
            name='salidas_esperadas',
            field=models.TextField(default=0, help_text='Salidas esperadas separadas por líneas'),
            preserve_default=False,
        ),
    ]
