# Generated by Django 5.1.6 on 2025-02-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juez', '0004_problema_entradas_prueba_problema_salidas_esperadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='ip_creacion',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
