# Generated by Django 5.1.6 on 2025-02-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juez', '0008_remove_problema_entradas_prueba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='entradas_prueba',
            field=models.TextField(default=0, help_text='Entradas de prueba separadas por líneas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problema',
            name='salidas_esperadas',
            field=models.TextField(default=0, help_text='Salidas esperadas separadas por líneas'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CasoPrueba',
        ),
    ]
