# Generated by Django 5.1.6 on 2025-02-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juez', '0009_problema_entradas_prueba_problema_salidas_esperadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='entradas_prueba',
            field=models.TextField(help_text='Entradas de prueba en formato JSON'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='salidas_esperadas',
            field=models.TextField(help_text='Salidas esperadas en formato JSON'),
        ),
    ]
