# Generated by Django 5.1.6 on 2025-02-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('entrada_ejemplo', models.TextField()),
                ('salida_ejemplo', models.TextField()),
                ('archivo_pruebas', models.FileField(blank=True, null=True, upload_to='pruebas/')),
            ],
        ),
    ]
